services:
  frontend:
    build: ./goraceloty-front-end
    depends_on:
      - service-hotel
    environment:
      - API_URL=http://service-hotel:8080
    ports:
      - "4200:80"
    networks:
      - goraceloty_net

  service-hotel:
    build: ./service-hotel
    depends_on:
      - db_postgres
    environment:
      - DATASOURCE_URL=db_postgres:5432/svc_hotel
      - DATASOURCE_USERNAME=gl_pg_user
      - DATASOURCE_PASSWORD=g0r4c3_l0ty
    ports:
      - "8080:8080"
    networks:
      - goraceloty_net

  service-offer:
    build: ./service-offer
    depends_on:
      - db_postgres
    environment:
      - DATASOURCE_URL=db_postgres:5432/svc_offer
      - DATASOURCE_USERNAME=gl_pg_user
      - DATASOURCE_PASSWORD=g0r4c3_l0ty
    ports:
      - "8081:8080"
    networks:
      - goraceloty_net

  db_postgres:
    image: postgres:14
    volumes:
      - ./pg-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: svc_offer, svc_hotel, svc_travel
      POSTGRES_USER: gl_pg_user
      POSTGRES_PASSWORD: g0r4c3_l0ty
    ports:
      - "5432:5432"
    networks:
      - goraceloty_net

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - goraceloty_net

networks:
  goraceloty_net:
    name: rsww_184372_net
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/16"
          gateway: "10.10.0.1"